tilt_controller_base:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_joint_base
    # joint_speed: 1.17
    joint_speed: 0.8
    motor:
        id: 1
        init: 512
        min: 0
        max: 1023

tilt_controller_trigger:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_joint_trigger
    # joint_speed: 1.17
    joint_speed: 2.2
    motor:
        id: 2
        init: 512
        min: 0
        max: 1023